### ISSUE TITLE
Crash when an axle or gear is placed on a MD mystical mechanics component.

### ISSUE THREAD

**Issue by Fiaegel** [DaedalusGame/MysticalMechanics#11]
This might be an issue of modular diversity, however the crash report blames this mod. Tested on modpack with latest forge and only jei, modular machinery/diversity and mystical mechanics installed to make sure.

Crash report: https://pastebin.com/rntT2ey5

**Comment by DaedalusGame** [comment]
https://github.com/DaedalusGame/Modular-Diversity/issues/32
