### ISSUE TITLE
Gearbox/Gear/Steam Engine/Etc Suggestions

### ISSUE THREAD

**Issue by TechnoMysterio** [DaedalusGame/MysticalMechanics#15]
Using the mechanical power system can be a little tedious, especially when having to place or design more complicated power generation and transfer setups. As such, I have a few suggestions to make to hopefully improve the system. I'm also including things about the Steam Engine here, since it only appears in Embers when MM is installed. So, some suggestions...

- Right-click placing a gearbox makes a gearbox face with the input toward you as per usual, but shift-right-click placing should invert this so that the gearbox is oriented with the input on the opposite side. Handy if you're working in tight spaces, so that you can get gearboxes facing the way you want them to from most positions.
- This behaviour would also be good if applied to the Steam Engine and the merger gearbox too. The steam engine especially, since I often like to place down axles first followed by an engine, and having to walk on top of the axle or just to the side of it in order to get the engine to output power to it is very finicky.
- Right-click inserting a gear into a gearbox (normal, merger, actuator) places it on the side you're looking at, shift-right-clicking a gear instead inserts it on the opposite face of the gearbox. This also applies to right-click and shift-right-click removal. This would be good if a gearbox is against a wall or some such, so you can get gears in tricky to reach sides.
- Holograms of gearboxes should appear before placing them, same for axles. Holograms for gear insertion would be good too, so that you can see where a gear is going to go into a gearbox before you insert it. This should account for right-click and shift-right-click modes. This would be good to make sure that players can see how something is oriented or where a gear will go without needing to go through the rigmarole of placing/breaking/replacing things.
- Clockwork attenuators don't seem to work with steam engines. This would be handy to change, so to allow more careful control of steam power systems.

This would be a good place to start with improving MM gearboxes, since while they are very fancy they can be annoying to work with if you don't know what you're getting into.

**Comment by DaedalusGame** [comment]
Pretty much all done (and released) other than the Embers specific suggestions
