### ISSUE TITLE
invalid update packet on block break

### ISSUE THREAD

**Issue by Dryxen** [DaedalusGame/MysticalMechanics#17]
Getting "Received invalid update packet for null tile entity at BlockPos........" in console any time a break a gear box or powered axle, appears to show up on the client side of things only. only tested currently in Dev environment. is this reproducible., if so ill do some more testing and look into the matter.

**Comment by DaedalusGame** [comment]
it is reproducible, it's a side effect of producing my own TE update packets when i need to update something to prevent sending a chunk update (chunk updates are laggy). It works fine despite the error, on both Embers and this, but if you want to look into it, the code is [here](https://github.com/DaedalusGame/MysticalMechanics/blob/master/src/main/java/mysticalmechanics/util/Misc.java#L17)

I feel like the answer might be trivial (just not sending an update packet if the te is gone) but idk

**Comment by Dryxen** [comment]
i see 2 options atm 1 being either dropping the sync all together and notifying the world for a block update or the method i prefer being instead of sending the old packet to the client just telling the client to update the chunk. will implement which ever method you prefer, both are working in dev.
edit:notifying is the proper standard way of updating the client though.

**Comment by DaedalusGame** [comment]
anything that triggers a chunk update is out of the question because it produces insane amounts of lag.
