### ISSUE TITLE
Audio/Visual Bug

### ISSUE THREAD

**Issue by XvBUSHvX** [DaedalusGame/MysticalMechanics#2]
Mystical Mechanics-0.2.jar
MC: 1.12.2
Forge: 2705

Gears when applied to the gear box don't appear until supplied power. Additionally there is no audio indicator when adding gears to a gear box only when removing them. 

Tested with only JEI and TOP included.

**Comment by DaedalusGame** [comment]
singleplayer or multiplayer?

**Comment by XvBUSHvX** [comment]
Single. I didn't set up a server just to check out a mod lol..

**Comment by DaedalusGame** [comment]
figures, checking now

**Comment by DaedalusGame** [comment]
can't seem to reproduce this in dev but i will try with TOP installed

**Comment by XvBUSHvX** [comment]
let me get a couple of screen caps.

**Comment by XvBUSHvX** [comment]
https://imgur.com/a/XTw7uJq

**Comment by DaedalusGame** [comment]
can't reproduce

**Comment by ghost** [comment]
i have the same problem with only Mystical Mechanics-0.2.jar installed.

**Comment by Dryxen** [comment]
Did some quick tests, in Version 0.5 the graphical error seems to be caused by division by 0. In TileEntityGearboxRenderer, removing line 21, and removing the reference to normPower on line 29  fixes the stationary rendering of gears in the gearbox powered or not.
