### ISSUE TITLE
Installing TechGuns and Mystical Mechanics causes 3D TechGuns items to lose their icons

### ISSUE THREAD

**Issue by Keyedrin** [DaedalusGame/MysticalMechanics#30]
When Mystical Mechanics is installed alongside TechGuns, the icons of TechGuns weapons and armor with 3D models are turned into missing textures. The items retain their 3D model texture, it is only inventory icons that disappear. Items without 3D models retain their icons, as do blocks.
This occurs with just TechGuns and Mystical Mechanics installed, and with both on their current release versions.

**Comment by Kataiser9** [comment]
To elaborate a little - at least for me, icons are fine in actual inventories (player inventory, chests, etc). It's only in JEI specifically where the icons are missing. Very odd.

**Comment by DaedalusGame** [comment]
https://github.com/pWn3d1337/Techguns2/issues/149 there's an issue open here, i don't know what in mystical mechanics would cause this, as i don't use ASM at all. it's probably on techguns side.

**Comment by DevTimur** [comment]
**Between version 0.5 and 0.6 there is list of changes**
- Adds The One Probe support
- Huge amount of fixes for edge cases. (Big thanks to Dryxen for more than half of these)
- Gearboxes and Axles can now be rotated
- Gearboxes can now be placed backwards if sneaking
- Gearboxes no longer split to disabled gears/gears with no output
- Fixes Mergeboxes staying on. (Dryxen)
- Fixes gears sometimes disappearing. (Dryxen)

**And you, DaedalusGame, did something....  and it broke rendering.
Can you remember what exactly did you do? For sure, 3 years have passed, but maybe SOMETHING you can remember?**

**Comment by wsfjm** [comment]
you can delete Mystical+Mechanics-0.1x.jar
/META-INF/mm_at.cfg
What does this code mean, but it solves the problem
