### ISSUE TITLE
Bug and crash with converter block

### ISSUE THREAD

**Issue by bloche1871** [DaedalusGame/MysticalMechanics#31]
Was testing out the following setup: BWM windmill - BWM axle - converter A - mystical mechanics axles - converter B - BWM axle - IE dynamo (using "better with engineering")

Noticed the dynamo didn't seem to generate power. Assumed it might be because of loss from the wooden gears (from mystical gears) I was using in the converters. Tried replacing the gear in converter B with an iron one and got the following crash:

https://paste.dimdev.org/qivigegudu.mccrash

**Comment by bloche1871** [comment]
Did some more testing without using BWE or BWG features and I seem to be getting crashes whenever I try setups where BWM axle power is converted to MM power then back to BWM, using converters:
https://paste.dimdev.org/vuhutuwuni.mccrash

**Comment by bloche1871** [comment]
Side question: is there a way to change the conversion ratio between MM & BWM axle power? It would be very useful to have a config for this.

**Comment by bloche1871** [comment]
Did more testing - even when it doesn't crash, putting more than one converter in series will make the axles keep rotating on their own even after removing all power sources

**Comment by DaedalusGame** [comment]
I can't reproduce the crash at all, but i'm dealing with the power feedback issue right now

**Comment by bloche1871** [comment]
Thank you! I hope it's ok if I create a new issue about adding a conversion ratio config. I have more details I can add.
