### ISSUE TITLE
change in rendering breaks special item rendering

### ISSUE THREAD

**Issue by RCXcrafter** [DaedalusGame/MysticalMechanics#35]
Items that use special rendering (like a TESR or a colorhandler) used to render perfectly fine when placed in a gearbox but no longer do. I'm pretty sure [**this**](https://github.com/DaedalusGame/MysticalMechanics/commit/f0184f29bf761863316cac49fa4186893d06c5b5#diff-725675138babd6737e5c3e4649068e7aR121) is the cause.
Left is before, right is after.
![image](https://user-images.githubusercontent.com/10962454/72839213-2745d080-3c92-11ea-88f0-2f4a78b86741.png)

**Comment by DaedalusGame** [comment]
oh no
